/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package operaciones;
import com.sun.awt.AWTUtilities;
import javax.swing.JOptionPane;
import operaciones.*; 

/**
 *
 * @author JESUS
 */
public class home extends  javax.swing.JFrame  {

    /**
     * Creates new form home
     */
    public home() {
       this.setUndecorated(true);
        initComponents();
       this.setLocationRelativeTo(this);
       AWTUtilities.setWindowOpaque(this,false);
       
        
    }
    

    int saldo = 100000; String clave = "6225"; 

public void menu(){ 

             String ingreso; 
             int op = 0; 
             do { 

                   ingreso = JOptionPane.showInputDialog(null, "1. Saldo de cuenta \n 2.  Consignar    \n 3.  Retirar       \n 4.  Cambio de clave       \n 5.  Salir");
if(ingreso != null && auxi.isNum(clave)){
        op = Integer.parseInt(ingreso); 
        switch(op) { 
                case 1: 
                      Saldo(); 
                        break;   
                  case 2: 
                         Consignar(); 
                          break; 
                   case 3: 
                          Retirar(); 
                           break; 
                    case 4: 
                          cambiarClave(); 
                          break; 
           } 
     }
     else{ 
             JOptionPane.showMessageDialog(null, "Digite la opción válida"); 
      } 
   } while (op!= 5); 
} 
public void Saldo(){ 
JOptionPane.showMessageDialog(null, "Tu saldo actual es de: $: "+saldo); 
} 
public void Consignar(){ 

        String con; 
        int consig = 0; 
        
        con = JOptionPane.showInputDialog(null, "¿Cuanto desea consignar: $:?");                         
        if(con!= null && !con.equals("") && auxi.isNum(con)){                                                                  
         consig = Integer.parseInt(con); 
         if(consig > 0){
                 saldo = saldo + consig; 
          } 
           else{ 
                  JOptionPane.showMessageDialog(null, "Consigne una cantidad mayor a 0"); 
           } 
   }
   else{ 
        JOptionPane.showMessageDialog(null, "Ingrese el valor a consignar"); 
    } 
} 
public void Retirar(){

          String ret = JOptionPane.showInputDialog(null,"Digite su clave");
           if(ret == null){ 
           } 
           else{
                   if(!ret.equals("")) {
                         if(ret.equals(clave)){ 
                             ret = JOptionPane.showInputDialog(null, "a. 5000 \n b. 10000     \n c.  20000   \n d. 50000      \n  e. 100000    \n f. Otro valor" , "CANTIDAD A RETIRAR", JOptionPane.INFORMATION_MESSAGE);  
if(ret != null){
if(!ret.equals("")){
switch(ret){
case "a": 
if(saldo - 5000 >= 10000){
 saldo = saldo - 5000; 
}
break; 
case "b": 
if(saldo - 10000 >= 10000){
       saldo = saldo - 10000; 
} 
break; 
case "c": 
if(saldo - 20000 >= 10000){
 saldo = saldo - 20000; 
} 
break; 
case "d": 
if(saldo - 50000 >= 10000){
 saldo = saldo - 50000; 
} 
break; 
case "e": 
if(saldo - 100000 >= 10000){
 saldo = saldo - 100000; 
} 
break; 
case "f": 
ret = JOptionPane.showInputDialog(null, "Digite el valor a retirar, $:");

          saldo -= Integer.parseInt(ret);
 
break;
default:

}
}
} 
} 
else { JOptionPane.showMessageDialog(null, "La clave no es correcta");
}
}
} 
}
public void cambiarClave() { 
String pass, ingresoClave; 
pass = JOptionPane.showInputDialog(null, "digite su clave: "); 
if(pass !=null){ 
if(!pass.equals("")){
if(pass.equals(clave)){
ingresoClave = JOptionPane.showInputDialog(null,"Digite la nueva clave:");
 if(ingresoClave !=null){
 if(ingresoClave.length()>3){ 

clave = ingresoClave; 
pass = "Su nueva clave es:" +clave; 
JOptionPane.showMessageDialog(null, pass); 
}   else  {
JOptionPane.showMessageDialog(null, "La clave es muy corta, se solicita el cambio"); 
  }
}
}  else {
JOptionPane.showMessageDialog(null, "La clave ingresada no es correcta"); 

}
}
}
}
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_ingresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(538, 303));
        setPreferredSize(new java.awt.Dimension(538, 303));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_ingresar.setText("ENTRAR");
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/operaciones/1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 558, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        // TODO add your handling code here:
        home inicio_cajero = new home();
        inicio_cajero.menu();
            
System.exit(0); 
    }//GEN-LAST:event_btn_ingresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
